<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="26" failed="0" total="26" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Regression Suite" duration-ms="29" started-at="2019-12-25T09:44:28Z" finished-at="2019-12-25T09:44:28Z">
    <groups>
    </groups>
    <test name="Regression Test" duration-ms="29" started-at="2019-12-25T09:44:28Z" finished-at="2019-12-25T09:44:28Z">
      <class name="tests.LoginTest">
        <test-method status="SKIP" signature="openLoginFormTest()[pri:0, instance:tests.LoginTest@79627d27]" name="openLoginFormTest" duration-ms="1" started-at="2019-12-25T11:44:28Z" finished-at="2019-12-25T11:44:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openLoginFormTest -->
        <test-method status="SKIP" signature="screenshotOnFailure(org.testng.ITestResult)[pri:0, instance:tests.LoginTest@79627d27]" name="screenshotOnFailure" is-config="true" duration-ms="0" started-at="2019-12-25T11:44:28Z" finished-at="2019-12-25T11:44:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOnFailure -->
        <test-method status="SKIP" signature="emptydataLoginFormTest()[pri:0, instance:tests.LoginTest@79627d27]" name="emptydataLoginFormTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.LoginTest.openLoginFormTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LoginTest.emptydataLoginFormTest()[pri:0, instance:tests.LoginTest@79627d27] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LoginTest.emptydataLoginFormTest()[pri:0, instance:tests.LoginTest@79627d27] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emptydataLoginFormTest -->
        <test-method status="SKIP" signature="emptyEmailFieldLoginFormTest()[pri:0, instance:tests.LoginTest@79627d27]" name="emptyEmailFieldLoginFormTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.LoginTest.emptydataLoginFormTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LoginTest.emptyEmailFieldLoginFormTest()[pri:0, instance:tests.LoginTest@79627d27] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LoginTest.emptyEmailFieldLoginFormTest()[pri:0, instance:tests.LoginTest@79627d27] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emptyEmailFieldLoginFormTest -->
        <test-method status="SKIP" signature="emptyPasswordFieldLoginFormTest()[pri:0, instance:tests.LoginTest@79627d27]" name="emptyPasswordFieldLoginFormTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.LoginTest.emptyEmailFieldLoginFormTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LoginTest.emptyPasswordFieldLoginFormTest()[pri:0, instance:tests.LoginTest@79627d27] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LoginTest.emptyPasswordFieldLoginFormTest()[pri:0, instance:tests.LoginTest@79627d27] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emptyPasswordFieldLoginFormTest -->
        <test-method status="SKIP" signature="makeLogoutTest()[pri:0, instance:tests.LoginTest@79627d27]" name="makeLogoutTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.LoginTest.makeLoginFormTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LoginTest.makeLogoutTest()[pri:0, instance:tests.LoginTest@79627d27] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LoginTest.makeLogoutTest()[pri:0, instance:tests.LoginTest@79627d27] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- makeLogoutTest -->
        <test-method status="SKIP" signature="makeLoginFormTest()[pri:0, instance:tests.LoginTest@79627d27]" name="makeLoginFormTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.LoginTest.emptyPasswordFieldLoginFormTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LoginTest.makeLoginFormTest()[pri:0, instance:tests.LoginTest@79627d27] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LoginTest.makeLoginFormTest()[pri:0, instance:tests.LoginTest@79627d27] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- makeLoginFormTest -->
      </class> <!-- tests.LoginTest -->
      <class name="tests.RequestPermitTest">
        <test-method status="SKIP" signature="openLoginFormTest()[pri:0, instance:tests.RequestPermitTest@b5b9333]" name="openLoginFormTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" finished-at="2019-12-25T11:44:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openLoginFormTest -->
        <test-method status="SKIP" signature="screenshotOnFailure(org.testng.ITestResult)[pri:0, instance:tests.RequestPermitTest@b5b9333]" name="screenshotOnFailure" is-config="true" duration-ms="0" started-at="2019-12-25T11:44:28Z" finished-at="2019-12-25T11:44:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOnFailure -->
        <test-method status="SKIP" signature="makeLoginFormTest()[pri:0, instance:tests.RequestPermitTest@b5b9333]" name="makeLoginFormTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.RequestPermitTest.openLoginFormTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RequestPermitTest.makeLoginFormTest()[pri:0, instance:tests.RequestPermitTest@b5b9333] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RequestPermitTest.makeLoginFormTest()[pri:0, instance:tests.RequestPermitTest@b5b9333] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- makeLoginFormTest -->
        <test-method status="SKIP" signature="requestPermitTest()[pri:0, instance:tests.RequestPermitTest@b5b9333]" name="requestPermitTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.RequestPermitTest.makeLoginFormTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RequestPermitTest.requestPermitTest()[pri:0, instance:tests.RequestPermitTest@b5b9333] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RequestPermitTest.requestPermitTest()[pri:0, instance:tests.RequestPermitTest@b5b9333] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- requestPermitTest -->
        <test-method status="SKIP" signature="selectPermitTypeTest()[pri:0, instance:tests.RequestPermitTest@b5b9333]" name="selectPermitTypeTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.RequestPermitTest.requestPermitTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RequestPermitTest.selectPermitTypeTest()[pri:0, instance:tests.RequestPermitTest@b5b9333] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RequestPermitTest.selectPermitTypeTest()[pri:0, instance:tests.RequestPermitTest@b5b9333] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectPermitTypeTest -->
        <test-method status="SKIP" signature="exportPermitRequestTest()[pri:0, instance:tests.RequestPermitTest@b5b9333]" name="exportPermitRequestTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.RequestPermitTest.selectPermitTypeTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RequestPermitTest.exportPermitRequestTest()[pri:0, instance:tests.RequestPermitTest@b5b9333] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RequestPermitTest.exportPermitRequestTest()[pri:0, instance:tests.RequestPermitTest@b5b9333] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exportPermitRequestTest -->
        <test-method status="SKIP" signature="makeLogoutTest()[pri:0, instance:tests.RequestPermitTest@b5b9333]" name="makeLogoutTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.RequestPermitTest.exportPermitRequestTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RequestPermitTest.makeLogoutTest()[pri:0, instance:tests.RequestPermitTest@b5b9333] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RequestPermitTest.makeLogoutTest()[pri:0, instance:tests.RequestPermitTest@b5b9333] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- makeLogoutTest -->
      </class> <!-- tests.RequestPermitTest -->
      <class name="tests.ExpiryDatesTest">
        <test-method status="SKIP" signature="openLoginFormTest()[pri:0, instance:tests.ExpiryDatesTest@52b959df]" name="openLoginFormTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" finished-at="2019-12-25T11:44:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openLoginFormTest -->
        <test-method status="SKIP" signature="makeLoginFormTest()[pri:0, instance:tests.ExpiryDatesTest@52b959df]" name="makeLoginFormTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.ExpiryDatesTest.openLoginFormTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ExpiryDatesTest.makeLoginFormTest()[pri:0, instance:tests.ExpiryDatesTest@52b959df] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ExpiryDatesTest.makeLoginFormTest()[pri:0, instance:tests.ExpiryDatesTest@52b959df] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- makeLoginFormTest -->
        <test-method status="SKIP" signature="screenshotOnFailure(org.testng.ITestResult)[pri:0, instance:tests.ExpiryDatesTest@52b959df]" name="screenshotOnFailure" is-config="true" duration-ms="0" started-at="2019-12-25T11:44:28Z" finished-at="2019-12-25T11:44:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOnFailure -->
        <test-method status="SKIP" signature="requestPermitTest()[pri:0, instance:tests.ExpiryDatesTest@52b959df]" name="requestPermitTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.ExpiryDatesTest.makeLoginFormTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ExpiryDatesTest.requestPermitTest()[pri:0, instance:tests.ExpiryDatesTest@52b959df] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ExpiryDatesTest.requestPermitTest()[pri:0, instance:tests.ExpiryDatesTest@52b959df] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- requestPermitTest -->
        <test-method status="SKIP" signature="makeLogoutTest()[pri:0, instance:tests.ExpiryDatesTest@52b959df]" name="makeLogoutTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.ExpiryDatesTest.requestPermitTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ExpiryDatesTest.makeLogoutTest()[pri:0, instance:tests.ExpiryDatesTest@52b959df] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ExpiryDatesTest.makeLogoutTest()[pri:0, instance:tests.ExpiryDatesTest@52b959df] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- makeLogoutTest -->
      </class> <!-- tests.ExpiryDatesTest -->
      <class name="tests.ExportRequestPermitTest">
        <test-method status="FAIL" signature="startDriver(java.lang.String)[pri:0, instance:tests.ExportRequestPermitTest@28e8888d]" name="startDriver" is-config="true" duration-ms="0" started-at="2019-12-25T11:44:12Z" finished-at="2019-12-25T11:44:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.SessionNotCreatedException">
            <message>
              <![CDATA[session not created
from chrome not reachable
  (Session info: chrome=79.0.3945.88)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-IQFTFHJ', ip: '192.168.8.134', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x00EEA923+1550627]
	Ordinal0 [0x00E6A731+1025841]
	Ordinal0 [0x00DEC5BE+509374]
	Ordinal0 [0x00DE62F2+484082]
	Ordinal0 [0x00DE69CB+485835]
	Ordinal0 [0x00DE7B35+490293]
	Ordinal0 [0x00DE3AB5+473781]
	Ordinal0 [0x00DED360+512864]
	Ordinal0 [0x00D9B649+177737]
	Ordinal0 [0x00D9A8ED+174317]
	Ordinal0 [0x00D98CDB+167131]
	Ordinal0 [0x00D8144A+70730]
	Ordinal0 [0x00D824D0+74960]
	Ordinal0 [0x00D82469+74857]
	Ordinal0 [0x00E842F7+1131255]
	GetHandleVerifier [0x00F8711D+523789]
	GetHandleVerifier [0x00F86EB0+523168]
	GetHandleVerifier [0x00F8E207+552695]
	GetHandleVerifier [0x00F8791A+525834]
	Ordinal0 [0x00E7B82C+1095724]
	Ordinal0 [0x00E8636B+1139563]
	Ordinal0 [0x00E864D3+1139923]
	Ordinal0 [0x00E85455+1135701]
	BaseThreadInitThunk [0x74C86359+25]
	RtlGetAppContainerNamedObjectPath [0x771E7B74+228]
	RtlGetAppContainerNamedObjectPath [0x771E7B44+180]
]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.SessionNotCreatedException: session not created
from chrome not reachable
  (Session info: chrome=79.0.3945.88)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-IQFTFHJ', ip: '192.168.8.134', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x00EEA923+1550627]
	Ordinal0 [0x00E6A731+1025841]
	Ordinal0 [0x00DEC5BE+509374]
	Ordinal0 [0x00DE62F2+484082]
	Ordinal0 [0x00DE69CB+485835]
	Ordinal0 [0x00DE7B35+490293]
	Ordinal0 [0x00DE3AB5+473781]
	Ordinal0 [0x00DED360+512864]
	Ordinal0 [0x00D9B649+177737]
	Ordinal0 [0x00D9A8ED+174317]
	Ordinal0 [0x00D98CDB+167131]
	Ordinal0 [0x00D8144A+70730]
	Ordinal0 [0x00D824D0+74960]
	Ordinal0 [0x00D82469+74857]
	Ordinal0 [0x00E842F7+1131255]
	GetHandleVerifier [0x00F8711D+523789]
	GetHandleVerifier [0x00F86EB0+523168]
	GetHandleVerifier [0x00F8E207+552695]
	GetHandleVerifier [0x00F8791A+525834]
	Ordinal0 [0x00E7B82C+1095724]
	Ordinal0 [0x00E8636B+1139563]
	Ordinal0 [0x00E864D3+1139923]
	Ordinal0 [0x00E85455+1135701]
	BaseThreadInitThunk [0x74C86359+25]
	RtlGetAppContainerNamedObjectPath [0x771E7B74+228]
	RtlGetAppContainerNamedObjectPath [0x771E7B44+180]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
	at tests.TestBase.startDriver(TestBase.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:521)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:296)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.SessionNotCreatedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startDriver -->
        <test-method status="SKIP" signature="openLoginFormTest()[pri:0, instance:tests.ExportRequestPermitTest@28e8888d]" name="openLoginFormTest" duration-ms="1" started-at="2019-12-25T11:44:28Z" finished-at="2019-12-25T11:44:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openLoginFormTest -->
        <test-method status="SKIP" signature="screenshotOnFailure(org.testng.ITestResult)[pri:0, instance:tests.ExportRequestPermitTest@28e8888d]" name="screenshotOnFailure" is-config="true" duration-ms="0" started-at="2019-12-25T11:44:28Z" finished-at="2019-12-25T11:44:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOnFailure -->
        <test-method status="SKIP" signature="exportPermitRequestTest()[pri:0, instance:tests.ExportRequestPermitTest@28e8888d]" name="exportPermitRequestTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.ExportRequestPermitTest.makeLoginFormTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ExportRequestPermitTest.exportPermitRequestTest()[pri:0, instance:tests.ExportRequestPermitTest@28e8888d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ExportRequestPermitTest.exportPermitRequestTest()[pri:0, instance:tests.ExportRequestPermitTest@28e8888d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exportPermitRequestTest -->
        <test-method status="SKIP" signature="makeLoginFormTest()[pri:0, instance:tests.ExportRequestPermitTest@28e8888d]" name="makeLoginFormTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.ExportRequestPermitTest.openLoginFormTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ExportRequestPermitTest.makeLoginFormTest()[pri:0, instance:tests.ExportRequestPermitTest@28e8888d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ExportRequestPermitTest.makeLoginFormTest()[pri:0, instance:tests.ExportRequestPermitTest@28e8888d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- makeLoginFormTest -->
        <test-method status="SKIP" signature="validFillExportPermitForm()[pri:0, instance:tests.ExportRequestPermitTest@28e8888d]" name="validFillExportPermitForm" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.ExportRequestPermitTest.exportPermitRequestTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ExportRequestPermitTest.validFillExportPermitForm()[pri:0, instance:tests.ExportRequestPermitTest@28e8888d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ExportRequestPermitTest.validFillExportPermitForm()[pri:0, instance:tests.ExportRequestPermitTest@28e8888d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validFillExportPermitForm -->
        <test-method status="SKIP" signature="makeLogoutTest()[pri:0, instance:tests.ExportRequestPermitTest@28e8888d]" name="makeLogoutTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.ExportRequestPermitTest.validFillExportPermitForm" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ExportRequestPermitTest.makeLogoutTest()[pri:0, instance:tests.ExportRequestPermitTest@28e8888d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ExportRequestPermitTest.makeLogoutTest()[pri:0, instance:tests.ExportRequestPermitTest@28e8888d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- makeLogoutTest -->
        <test-method status="SKIP" signature="stopDriver()[pri:0, instance:tests.ExportRequestPermitTest@28e8888d]" name="stopDriver" is-config="true" duration-ms="0" started-at="2019-12-25T11:44:28Z" finished-at="2019-12-25T11:44:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopDriver -->
      </class> <!-- tests.ExportRequestPermitTest -->
      <class name="tests.ForgetPasswordTest">
        <test-method status="SKIP" signature="openLoginFormTest()[pri:0, instance:tests.ForgetPasswordTest@6371cf2f]" name="openLoginFormTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" finished-at="2019-12-25T11:44:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openLoginFormTest -->
        <test-method status="SKIP" signature="screenshotOnFailure(org.testng.ITestResult)[pri:0, instance:tests.ForgetPasswordTest@6371cf2f]" name="screenshotOnFailure" is-config="true" duration-ms="0" started-at="2019-12-25T11:44:28Z" finished-at="2019-12-25T11:44:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOnFailure -->
        <test-method status="SKIP" signature="openForgetPasswordFormTest()[pri:0, instance:tests.ForgetPasswordTest@6371cf2f]" name="openForgetPasswordFormTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.ForgetPasswordTest.openLoginFormTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ForgetPasswordTest.openForgetPasswordFormTest()[pri:0, instance:tests.ForgetPasswordTest@6371cf2f] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ForgetPasswordTest.openForgetPasswordFormTest()[pri:0, instance:tests.ForgetPasswordTest@6371cf2f] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openForgetPasswordFormTest -->
        <test-method status="SKIP" signature="emptydataForgetPasswordFormTest()[pri:0, instance:tests.ForgetPasswordTest@6371cf2f]" name="emptydataForgetPasswordFormTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.ForgetPasswordTest.openForgetPasswordFormTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ForgetPasswordTest.emptydataForgetPasswordFormTest()[pri:0, instance:tests.ForgetPasswordTest@6371cf2f] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ForgetPasswordTest.emptydataForgetPasswordFormTest()[pri:0, instance:tests.ForgetPasswordTest@6371cf2f] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emptydataForgetPasswordFormTest -->
        <test-method status="SKIP" signature="invalidDataForgetPasswordFormTest()[pri:0, instance:tests.ForgetPasswordTest@6371cf2f]" name="invalidDataForgetPasswordFormTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.ForgetPasswordTest.emptydataForgetPasswordFormTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ForgetPasswordTest.invalidDataForgetPasswordFormTest()[pri:0, instance:tests.ForgetPasswordTest@6371cf2f] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ForgetPasswordTest.invalidDataForgetPasswordFormTest()[pri:0, instance:tests.ForgetPasswordTest@6371cf2f] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidDataForgetPasswordFormTest -->
        <test-method status="SKIP" signature="forgetPasswordFormTest()[pri:0, instance:tests.ForgetPasswordTest@6371cf2f]" name="forgetPasswordFormTest" duration-ms="0" started-at="2019-12-25T11:44:28Z" depends-on-methods="tests.ForgetPasswordTest.invalidDataForgetPasswordFormTest" finished-at="2019-12-25T11:44:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ForgetPasswordTest.forgetPasswordFormTest()[pri:0, instance:tests.ForgetPasswordTest@6371cf2f] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ForgetPasswordTest.forgetPasswordFormTest()[pri:0, instance:tests.ForgetPasswordTest@6371cf2f] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgetPasswordFormTest -->
      </class> <!-- tests.ForgetPasswordTest -->
    </test> <!-- Regression Test -->
  </suite> <!-- Regression Suite -->
</testng-results>
